
def dpimerge_config(match_inputs,**kwargs):
    from path_helper import PathHelper
    version_of_collection=dict(match_inputs)
    out_stems = []
    fetch_list = []
    args = []
    import re
    has_version = re.compile(r'.*\.v\d+$')
    combo_dpis = kwargs.pop('combo_dpi',tuple())
    out_stem_lookup = {}
    for output in sorted(kwargs):
        ingredients = kwargs[output]
        out_stem = f'matching.{output}.VERSION.dpimerge.tsv'
        out_stems.append(out_stem)
        out_stem_lookup[output] = out_stem # save for combos
        if args:
            args.append('+')
        args.append(out_stem)
        for src in ingredients:
            parts = src.split('.')
            if parts[0] in ('dpi','c50','ki'):
                # legacy filename, no version
                in_file = f'stage_dpi/{src}.tsv_processed.tsv'
                # don't attempt to fetch these
            else:
                if has_version.match(src):
                    # this is a legacy case to reproduce v4, in which
                    # one dpi input had a mis-configured version; we
                    # don't generally want to use different versions
                    # for dpimerge than we use for matching, but we
                    # also don't want to mis-represent what's in the
                    # older files
                    pass
                else:
                    # add in version
                    src = src+'.'+version_of_collection[parts[0]]
                in_file = PathHelper.storage + f'{parts[0]}/{src}.evidence.tsv'
                fetch_list.append(in_file)
            args.append(in_file)
    combo_inputs = set()
    combo_outputs = []
    for output in sorted(combo_dpis):
        out_stem = f'matching.{output}.VERSION.dpimerge.tsv'
        combo_outputs.append(out_stem)
        src_dpi,base_drug = output.split('+')
        combo_inputs.add(out_stem_lookup[src_dpi])
    # deduplicate fetch list (an input used in multiple dpimerge outputs
    # will appear multiple times otherwise, which is not a problem for
    # the Makefile, but makes output less readable)
    fetch_list = sorted(set(fetch_list))
    # ditto with combo_inputs
    combo_inputs = sorted(set(combo_inputs))

    # Not doing combo here; probably easier to run combo on top of moa rather
    # than vice-versa, to preserve attr/key names, but defer until needed.
    moa_out = [x.replace('.VERSION', '-moa.VERSION') for x in out_stems]

    # Add sqlite outputs for fast lookup to live alongside the tsvs.
    out_stems += [x.replace('.tsv', '.sqlsv') for x in out_stems]
    combo_outputs += [x.replace('.tsv', '.sqlsv') for x in combo_outputs]
    moa_out += [x.replace('.tsv', '.sqlsv') for x in moa_out]
    from dtk.s3_cache import attribute_file_name as coll
    return dict(
            DPIMERGE_OUT_STEMS=' '.join(out_stems),
            DPIMERGE_ARG_STEMS=' '.join(args),
            COMBO_OUT_STEMS=' '.join(combo_outputs),
            COMBO_IN_STEMS=' '.join(combo_inputs),
            MOA_OUT_STEMS=' '.join(moa_out),
            DPIMERGE_INPUTS=' '.join(fetch_list),
            MATCH_INPUTS=' '.join([coll(*x) for x in match_inputs]),
            **{c.upper()+'_VER':v for c,v in match_inputs}
            )



versions = {
                46:dict(
                                description='21Dec2022 DUMA update',
                                UNIPROT_VER='15',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v19'),
                                                                ('drugbank','v19'),
                                                                ('duma','v40'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v16'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v12'),
                                                                ('lincs','v4'),
                                                                ('globaldata','v3'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                'globaldata.default',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                45:dict(
                                description='Dec2022 ETL refresh',
                                UNIPROT_VER='15',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v19'),
                                                                ('drugbank','v19'),
                                                                ('duma','v39'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v16'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v12'),
                                                                ('lincs','v4'),
                                                                ('globaldata','v3'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                'globaldata.default',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                44:dict(
                                description='v38 Duma update',
                                UNIPROT_VER='14',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v18'),
                                                                ('drugbank','v18'),
                                                                ('duma','v38'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v15'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v11'),
                                                                ('lincs','v4'),
                                                                ('globaldata','v2'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                'globaldata.default',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                43:dict(
                                description='v37 Duma update',
                                UNIPROT_VER='14',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v18'),
                                                                ('drugbank','v18'),
                                                                ('duma','v37'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v15'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v11'),
                                                                ('lincs','v4'),
                                                                ('globaldata','v2'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                'globaldata.default',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                42:dict(
                                description='Sep2022 ETL refresh',
                                UNIPROT_VER='14',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v18'),
                                                                ('drugbank','v18'),
                                                                ('duma','v36'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v15'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v11'),
                                                                ('lincs','v4'),
                                                                ('globaldata','v2'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                'globaldata.default',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                41:dict(
                                description='DUMA v35 update',
                                UNIPROT_VER='13',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v17'),
                                                                ('drugbank','v17'),
                                                                ('duma','v35'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v14'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v10'),
                                                                ('lincs','v4'),
                                                                ('globaldata','v1'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                'globaldata.default',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                40:dict(
                                description='DUMA v34 update',
                                UNIPROT_VER='13',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v17'),
                                                                ('drugbank','v17'),
                                                                ('duma','v34'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v14'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v10'),
                                                                ('lincs','v4'),
                                                                ('globaldata','v1'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                'globaldata.default',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                39:dict(
                                description='DUMA v33 update',
                                UNIPROT_VER='13',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v17'),
                                                                ('drugbank','v17'),
                                                                ('duma','v33'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v14'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v10'),
                                                                ('lincs','v4'),
                                                                ('globaldata','v1'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                'globaldata.default',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                38:dict(
                                description='1Jun2022 ETL refresh',
                                UNIPROT_VER='13',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v17'),
                                                                ('drugbank','v17'),
                                                                ('duma','v32'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v14'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v10'),
                                                                ('lincs','v4'),
                                                                ('globaldata','v1'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                'globaldata.default',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                37:dict(
                                description='DUMA v31 update',
                                UNIPROT_VER='12',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v16'),
                                                                ('drugbank','v16'),
                                                                ('duma','v31'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v13'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v9'),
                                                                ('lincs','v4'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                36:dict(
                                description='1Mar2022 ETL refresh',
                                UNIPROT_VER='12',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v16'),
                                                                ('drugbank','v16'),
                                                                ('duma','v30'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v13'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v9'),
                                                                ('lincs','v4'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                35:dict(
                                description='Latest DUMA collection update',
                                UNIPROT_VER='12',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v15'),
                                                                ('drugbank','v15'),
                                                                ('duma','v29'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v12'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v8'),
                                                                ('lincs','v4'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                34:dict(
                                description='Latest DUMA collection update',
                                UNIPROT_VER='12',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v15'),
                                                                ('drugbank','v15'),
                                                                ('duma','v28'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v12'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v8'),
                                                                ('lincs','v4'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                33:dict(
                                description='1Dec2021 ETL refresh',
                                UNIPROT_VER='12',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v15'),
                                                                ('drugbank','v15'),
                                                                ('duma','v27'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v12'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v8'),
                                                                ('lincs','v4'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                32:dict(
                                description='18Oct2021 latest duma collection update',
                                UNIPROT_VER='11',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v14'),
                                                                ('drugbank','v14'),
                                                                ('duma','v26'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v12'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v7'),
                                                                ('lincs','v4'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),

                                ),
                31:dict(
                                description='16Aug2021 ETL update',
                                UNIPROT_VER='11',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v14'),
                                                                ('drugbank','v14'),
                                                                ('duma','v25'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v12'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v7'),
                                                                ('lincs','v4'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),

                                ),
                30:dict(
                                description='Latest duma refresh',
                                UNIPROT_VER='10',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v13'),
                                                                ('drugbank','v13'),
                                                                ('duma','v23'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v11'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v6'),
                                                                ('lincs','v3'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                29:dict(
                                description='Latest duma refresh',
                                UNIPROT_VER='10',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v13'),
                                                                ('drugbank','v13'),
                                                                ('duma','v22'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v11'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v6'),
                                                                ('lincs','v3'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                28:dict(
                                description='1Jun2021 ETL update',
                                UNIPROT_VER='10',
                                **dpimerge_config(
                                                match_inputs=[
                                                                ('chembl','v13'),
                                                                ('drugbank','v13'),
                                                                ('duma','v21'),
                                                                ('ncats','v1'),
                                                                ('bindingdb','v11'),
                                                                ('med_chem_express','v7'),
                                                                ('selleckchem','v8'),
                                                                ('cayman','v6'),
                                                                ('pubchem','v6'),
                                                                ('lincs','v3'),
                                                                ],
                                                DNChBX_ki=(
                                                                'duma.default',
                                                                'drugbank.default',
                                                                'ncats.default',
                                                                'chembl.c50',
                                                                'chembl.ki',
                                                                'bindingdb.c50',
                                                                'bindingdb.ki',
                                                                'lincs.full',
                                                                ),
                                                combo_dpi=(
                                                                ),
                                                ),
                                ),
                27:dict(
                        description='Add std_smiles to LINCS',
                        UNIPROT_VER='8',
                        **dpimerge_config(
                                        match_inputs=[
                                                        ('chembl','v12'),
                                                        ('drugbank','v12'),
                                                        ('duma','v20'),
                                                        ('ncats','v1'),
                                                        ('bindingdb','v10'),
                                                        ('med_chem_express','v7'),
                                                        ('selleckchem','v8'),
                                                        ('cayman','v5'),
                                                        ('pubchem','v5'),
                                                        ('lincs','v2'),
                                                        ],
                                        DNChBX_ki=(
                                                        'duma.default',
                                                        'drugbank.default',
                                                        'ncats.default',
                                                        'chembl.c50',
                                                        'chembl.ki',
                                                        'bindingdb.c50',
                                                        'bindingdb.ki',
                                                        'lincs.full',
                                                        ),
                                        combo_dpi=(
                                                        ),
                                        ),
                        ),
                26:dict(
                        description='Adding LINCS',
                        UNIPROT_VER='8',
                        **dpimerge_config(
                                          match_inputs=[
                                                        ('chembl','v12'),
                                                        ('drugbank','v12'),
                                                        ('duma','v20'),
                                                        ('ncats','v1'),
                                                        ('bindingdb','v10'),
                                                        ('med_chem_express','v7'),
                                                        ('selleckchem','v8'),
                                                        ('cayman','v5'),
                                                        ('pubchem','v5'),
                                                        ('lincs','v1'),
                                                        ],
                                           DNChBX_ki=(
                                                      'duma.default',
                                                      'drugbank.default',
                                                      'ncats.default',
                                                      'chembl.c50',
                                                      'chembl.ki',
                                                      'bindingdb.c50',
                                                      'bindingdb.ki',
                                                      'lincs.full',
                                                      ),
                                           combo_dpi=(
                                                      ),
                                           ),
                           ),
                25:dict(
                        description='Latest DUMA',
                        UNIPROT_VER='8',
                        **dpimerge_config(
                                          match_inputs=[
                                                        ('chembl','v12'),
                                                        ('drugbank','v12'),
                                                        ('duma','v20'),
                                                        ('ncats','v1'),
                                                        ('bindingdb','v10'),
                                                        ('med_chem_express','v7'),
                                                        ('selleckchem','v8'),
                                                        ('cayman','v5'),
                                                        ('pubchem','v5'),
                                                        ],
                                           DNChBX_ki=(
                                                      'duma.default',
                                                      'drugbank.default',
                                                      'ncats.default',
                                                      'chembl.c50',
                                                      'chembl.ki',
                                                      'bindingdb.c50',
                                                      'bindingdb.ki',
                                                      ),
                                           combo_dpi=(
                                                      'DNChBX_ki+Crizotinib',
                                                      'DNChBX_ki+Gemcitabine',
                                                      'DNChBX_ki+Lapatinib',
                                                      'DNChBX_ki+Trametinib',
                                                      ),
                                           ),
                           ),
                24:dict(
                        description='Latest DUMA',
                        UNIPROT_VER='8',
                        **dpimerge_config(
                                          match_inputs=[
                                                        ('chembl','v12'),
                                                        ('drugbank','v12'),
                                                        ('duma','v19'),
                                                        ('ncats','v1'),
                                                        ('bindingdb','v10'),
                                                        ('med_chem_express','v7'),
                                                        ('selleckchem','v8'),
                                                        ('cayman','v5'),
                                                        ('pubchem','v5'),
                                                        ],
                                           DNChBX_ki=(
                                                      'duma.default',
                                                      'drugbank.default',
                                                      'ncats.default',
                                                      'chembl.c50',
                                                      'chembl.ki',
                                                      'bindingdb.c50',
                                                      'bindingdb.ki',
                                                      ),
                                           combo_dpi=(
                                                      'DNChBX_ki+Crizotinib',
                                                      'DNChBX_ki+Gemcitabine',
                                                      'DNChBX_ki+Lapatinib',
                                                      'DNChBX_ki+Trametinib',
                                                      ),
                                           ),
                           ),
                23:dict(
                        description='1Mar2021 ETL Refresh',
                        UNIPROT_VER='8',
                        **dpimerge_config(
                                          match_inputs=[
                                                        ('chembl','v12'),
                                                        ('drugbank','v12'),
                                                        ('duma','v18'),
                                                        ('ncats','v1'),
                                                        ('bindingdb','v10'),
                                                        ('med_chem_express','v7'),
                                                        ('selleckchem','v8'),
                                                        ('cayman','v5'),
                                                        ('pubchem','v5'),
                                                        ],
                                           DNChBX_ki=(
                                                      'duma.default',
                                                      'drugbank.default',
                                                      'ncats.default',
                                                      'chembl.c50',
                                                      'chembl.ki',
                                                      'bindingdb.c50',
                                                      'bindingdb.ki',
                                                      ),
                                           combo_dpi=(
                                                      'DNChBX_ki+Crizotinib',
                                                      'DNChBX_ki+Gemcitabine',
                                                      'DNChBX_ki+Lapatinib',
                                                      'DNChBX_ki+Trametinib',
                                                      ),
                                           ),
                           ),
        22:dict(
                description='Latest DUMA, and adding new ChEMBL filtered MoAs',
                UNIPROT_VER='7',
                **dpimerge_config(
                                match_inputs=[
                                                ('chembl','v11'),
                                                ('drugbank','v11'),
                                                ('duma','v17'),
                                                ('ncats','v1'),
                                                ('bindingdb','v9'),
                                                ('med_chem_express','v6'),
                                                ('selleckchem','v7'),
                                                ('cayman','v5'),
                                                ('pubchem','v4'),
                                                ],
                                DNChBX_ki=(
                                                'duma.default',
                                                'drugbank.default',
                                                'ncats.default',
                                                'chembl.c50',
                                                'chembl.ki',
                                                'bindingdb.c50',
                                                'bindingdb.ki',
                                                ),
                                combo_dpi=(
                                                'DNChBX_ki+Crizotinib',
                                                'DNChBX_ki+Gemcitabine',
                                                'DNChBX_ki+Lapatinib',
                                                'DNChBX_ki+Trametinib',
                                                ),
                                ),
                ),
        21:dict(
                description='Updated normalization',
                UNIPROT_VER='7',
                **dpimerge_config(
                                match_inputs=[
                                                ('chembl','v10'),
                                                ('drugbank','v11'),
                                                ('duma','v16'),
                                                ('ncats','v1'),
                                                ('bindingdb','v9'),
                                                ('med_chem_express','v6'),
                                                ('selleckchem','v7'),
                                                ('cayman','v5'),
                                                ('pubchem','v4'),
                                                ],
                                DNChBX_ki=(
                                                'duma.default',
                                                'drugbank.default',
                                                'ncats.default',
                                                'chembl.c50',
                                                'chembl.ki',
                                                'bindingdb.c50',
                                                'bindingdb.ki',
                                                ),
                                combo_dpi=(
                                                'DNChBX_ki+Crizotinib',
                                                'DNChBX_ki+Gemcitabine',
                                                'DNChBX_ki+Lapatinib',
                                                'DNChBX_ki+Trametinib',
                                                ),
                                ),
                ),
        20:dict(
                description='2021-01-20 Duma Update',
                UNIPROT_VER='7',
                **dpimerge_config(
                                match_inputs=[
                                                ('chembl','v9'),
                                                ('drugbank','v10'),
                                                ('duma','v15'),
                                                ('ncats','v1'),
                                                ('bindingdb','v8'),
                                                ('med_chem_express','v6'),
                                                ('selleckchem','v6'),
                                                ('cayman','v4'),
                                                ('pubchem','v3'),
                                                ],
                                DNChBX_ki=(
                                                'duma.default',
                                                'drugbank.default',
                                                'ncats.default',
                                                'chembl.c50',
                                                'chembl.ki',
                                                'bindingdb.c50',
                                                'bindingdb.ki',
                                                ),
                                combo_dpi=(
                                                'DNChBX_ki+Crizotinib',
                                                'DNChBX_ki+Gemcitabine',
                                                'DNChBX_ki+Lapatinib',
                                                'DNChBX_ki+Trametinib',
                                                ),
                                ),
                ),
        19:dict(
                description='10Dec2020 ETL Refresh',
                UNIPROT_VER='7',
                **dpimerge_config(
                                match_inputs=[
                                                ('chembl','v9'),
                                                ('drugbank','v10'),
                                                ('duma','v14'),
                                                ('ncats','v1'),
                                                ('bindingdb','v8'),
                                                ('med_chem_express','v6'),
                                                ('selleckchem','v6'),
                                                ('cayman','v4'),
                                                ('pubchem','v3'),
                                                ],
                                DNChBX_ki=(
                                                'duma.default',
                                                'drugbank.default',
                                                'ncats.default',
                                                'chembl.c50',
                                                'chembl.ki',
                                                'bindingdb.c50',
                                                'bindingdb.ki',
                                                ),
                                combo_dpi=(
                                                'DNChBX_ki+Crizotinib',
                                                'DNChBX_ki+Gemcitabine',
                                                'DNChBX_ki+Lapatinib',
                                                'DNChBX_ki+Trametinib',
                                                ),
                                ),
                ),
        18:dict(
                description='Fixed MoA DPI, removed 0.4 ki evid',
                UNIPROT_VER='6',
                **dpimerge_config(
                                match_inputs=[
                                                ('chembl','v8'),
                                                ('drugbank','v9'),
                                                ('duma','v13'),
                                                ('ncats','v1'),
                                                ('bindingdb','v7'),
                                                ('med_chem_express','v5'),
                                                ('selleckchem','v5'),
                                                ('cayman','v4'),
                                                ('pubchem','v2'),
                                                ],
                                DNChBX_ki=(
                                                'duma.default',
                                                'drugbank.default',
                                                'ncats.default',
                                                'chembl.c50',
                                                'chembl.ki',
                                                'bindingdb.c50',
                                                'bindingdb.ki',
                                                ),
                                combo_dpi=(
                                                'DNChBX_ki+Crizotinib',
                                                'DNChBX_ki+Gemcitabine',
                                                'DNChBX_ki+Lapatinib',
                                                'DNChBX_ki+Trametinib',
                                                ),
                                ),
                ),
        17:dict(
                description='Duma update',
                UNIPROT_VER='6',
                **dpimerge_config(
                                match_inputs=[
                                                ('chembl','v8'),
                                                ('drugbank','v9'),
                                                ('duma','v13'),
                                                ('ncats','v1'),
                                                ('bindingdb','v7'),
                                                ('med_chem_express','v5'),
                                                ('selleckchem','v5'),
                                                ('cayman','v4'),
                                                ('pubchem','v2'),
                                                ],
                                DNChBX_ki=(
                                                'duma.default',
                                                'drugbank.default',
                                                'ncats.default',
                                                'chembl.c50',
                                                'chembl.ki',
                                                'bindingdb.c50',
                                                'bindingdb.ki',
                                                ),
                                combo_dpi=(
                                                'DNChBX_ki+Crizotinib',
                                                'DNChBX_ki+Gemcitabine',
                                                'DNChBX_ki+Lapatinib',
                                                'DNChBX_ki+Trametinib',
                                                ),
                                ),
                ),
        16:dict(
                description='Duma update',
                UNIPROT_VER='6',
                **dpimerge_config(
                                match_inputs=[
                                                ('chembl','v8'),
                                                ('drugbank','v9'),
                                                ('duma','v12'),
                                                ('ncats','v1'),
                                                ('bindingdb','v7'),
                                                ('med_chem_express','v5'),
                                                ('selleckchem','v5'),
                                                ('cayman','v4'),
                                                ('pubchem','v2'),
                                                ],
                                DNChBX_ki=(
                                                'duma.default',
                                                'drugbank.default',
                                                'ncats.default',
                                                'chembl.c50',
                                                'chembl.ki',
                                                'bindingdb.c50',
                                                'bindingdb.ki',
                                                ),
                                combo_dpi=(
                                                'DNChBX_ki+Crizotinib',
                                                'DNChBX_ki+Gemcitabine',
                                                'DNChBX_ki+Lapatinib',
                                                'DNChBX_ki+Trametinib',
                                                ),
                                ),
                ),
        15:dict(
                description='Duma update',
                UNIPROT_VER='6',
                **dpimerge_config(
                                match_inputs=[
                                                ('chembl','v8'),
                                                ('drugbank','v9'),
                                                ('duma','v11'),
                                                ('ncats','v1'),
                                                ('bindingdb','v7'),
                                                ('med_chem_express','v5'),
                                                ('selleckchem','v5'),
                                                ('cayman','v4'),
                                                ('pubchem','v2'),
                                                ],
                                DNChBX_ki=(
                                                'duma.default',
                                                'drugbank.default',
                                                'ncats.default',
                                                'chembl.c50',
                                                'chembl.ki',
                                                'bindingdb.c50',
                                                'bindingdb.ki',
                                                ),
                                combo_dpi=(
                                                'DNChBX_ki+Crizotinib',
                                                'DNChBX_ki+Gemcitabine',
                                                'DNChBX_ki+Lapatinib',
                                                'DNChBX_ki+Trametinib',
                                                ),
                                ),
                ),
        14:dict(
                description='4Sep2020 ETL update',
                UNIPROT_VER='6',
                **dpimerge_config(
                                match_inputs=[
                                                ('chembl','v8'),
                                                ('drugbank','v9'),
                                                ('duma','v10'),
                                                ('ncats','v1'),
                                                ('bindingdb','v7'),
                                                ('med_chem_express','v5'),
                                                ('selleckchem','v5'),
                                                ('cayman','v4'),
                                                ('pubchem','v2'),
                                                ],
                                DNChBX_ki=(
                                                'duma.default',
                                                'drugbank.default',
                                                'ncats.default',
                                                'chembl.c50',
                                                'chembl.ki',
                                                'bindingdb.c50',
                                                'bindingdb.ki',
                                                ),
                                combo_dpi=(
                                                'DNChBX_ki+Crizotinib',
                                                'DNChBX_ki+Gemcitabine',
                                                'DNChBX_ki+Lapatinib',
                                                'DNChBX_ki+Trametinib',
                                                ),
                                ),
                ),
        13:dict(
                description='Duma Updated',
                **dpimerge_config(
                        match_inputs=[
                                ('chembl','v7'),
                                ('drugbank','v8'), 
                                ('duma','v9'),
                                ('ncats','v1'),
                                ('bindingdb','v6'),
                                ('med_chem_express','v4'),
                                ('selleckchem','v4'),
                                ('cayman','v3'),
                                ('pubchem','v1'),
                                ],
                        DNChBX_ki=(
                                'duma.default',
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                'chembl.ki',
                                'bindingdb.c50',
                                'bindingdb.ki',
                                ),
                        combo_dpi=(
                                'DNChBX_ki+Trametinib',
                                'DNChBX_ki+Lapatinib',
                                'DNChBX_ki+Crizotinib',
                                'DNChBX_ki+Gemcitabine',
                                ),
                        ),
                ),
        12:dict(
                description='Duma Updated',
                **dpimerge_config(
                        match_inputs=[
                                ('chembl','v6'),
                                ('drugbank','v8'), 
                                ('duma','v8'),
                                ('ncats','v1'),
                                ('bindingdb','v6'),
                                ('med_chem_express','v4'),
                                ('selleckchem','v4'),
                                ('cayman','v3'),
                                ('pubchem','v1'),
                                ],
                        DNChBX_ki=(
                                'duma.default',
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                'chembl.ki',
                                'bindingdb.c50',
                                'bindingdb.ki',
                                ),
                        combo_dpi=(
                                'DNChBX_ki+Trametinib',
                                'DNChBX_ki+Lapatinib',
                                'DNChBX_ki+Crizotinib',
                                'DNChBX_ki+Gemcitabine',
                                ),
                        ),
                ),
        11:dict(
                description='PubChem added',
                **dpimerge_config(
                        match_inputs=[
                                ('chembl','v6'),
                                ('drugbank','v8'), 
                                ('duma','v7'),
                                ('ncats','v1'),
                                ('bindingdb','v6'),
                                ('med_chem_express','v4'),
                                ('selleckchem','v4'),
                                ('cayman','v3'),
                                ('pubchem','v1'),
                                ],
                        DNChBX_ki=(
                                'duma.default',
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                'chembl.ki',
                                'bindingdb.c50',
                                'bindingdb.ki',
                                ),
                        combo_dpi=(
                                'DNChBX_ki+Trametinib',
                                'DNChBX_ki+Lapatinib',
                                'DNChBX_ki+Crizotinib',
                                ),
                        ),
                ),
        10:dict(
                description='Standard ETL refresh',
                **dpimerge_config(
                        match_inputs=[
                                ('chembl','v6'),
                                ('drugbank','v5'),
                                ('duma','v7'),
                                ('ncats','v1'),
                                ('bindingdb','v6'),
                                ('med_chem_express','v4'),
                                ('selleckchem','v4'),
                                ('cayman','v3'),
                                ],
                        DNChBX_ki=(
                                'duma.default',
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                'chembl.ki',
                                'bindingdb.c50',
                                'bindingdb.ki',
                                ),
                        combo_dpi=(
                                'DNChBX_ki+Trametinib',
                                'DNChBX_ki+Lapatinib',
                                'DNChBX_ki+Crizotinib',
                                ),
                        ),
                ),
        9:dict(
                description='Update ChEMBL with comm mols',
                **dpimerge_config(
                        match_inputs=[
                                ('chembl','v5'),
                                ('drugbank','v4'),
                                ('duma','v6'),
                                ('ncats','v1'),
                                ('bindingdb','v5'),
                                ('med_chem_express','v3'),
                                ('selleckchem','v3'),
                                ('cayman','v2'),
                                ],
                        DNChBX_ki=(
                                'duma.default',
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                'chembl.ki',
                                'bindingdb.c50',
                                'bindingdb.ki',
                                ),
                        combo_dpi=(
                                'DNChBX_ki+Trametinib',
                                'DNChBX_ki+Lapatinib',
                                'DNChBX_ki+Crizotinib',
                                ),
                        ),
                ),
        8:dict(
                description='Update ChEMBL with clin mols',
                **dpimerge_config(
                        match_inputs=[
                                ('chembl','v4'),
                                ('drugbank','v4'),
                                ('duma','v6'),
                                ('ncats','v1'),
                                ('bindingdb','v5'),
                                ('med_chem_express','v3'),
                                ('selleckchem','v3'),
                                ('cayman','v2'),
                                ],
                        DNChBX_ki=(
                                'duma.default',
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                'chembl.ki',
                                'bindingdb.c50',
                                'bindingdb.ki',
                                ),
                        combo_dpi=(
                                'DNChBX_ki+Trametinib',
                                'DNChBX_ki+Lapatinib',
                                'DNChBX_ki+Crizotinib',
                                ),
                        ),
                ),
        7:dict(
                description='Update Uniprot',
                **dpimerge_config(
                        match_inputs=[
                                ('chembl','v3'),
                                ('drugbank','v3'),
                                ('duma','v6'),
                                ('ncats','v1'),
                                ('bindingdb','v5'),
                                ('med_chem_express','v3'),
                                ('selleckchem','v3'),
                                ('cayman','v2'),
                                ],
                        DNChBX_ki=(
                                'duma.default',
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                'chembl.ki',
                                'bindingdb.c50',
                                'bindingdb.ki',
                                ),
                        combo_dpi=(
                                'DNChBX_ki+Trametinib',
                                'DNChBX_ki+Lapatinib',
                                'DNChBX_ki+Crizotinib',
                                ),
                        ),
                ),
        6:dict(
                description='Update DUMA',
                **dpimerge_config(
                        match_inputs=[
                                ('chembl','v2'),
                                ('drugbank','v2'),
                                ('duma','v5'),
                                ('ncats','v1'),
                                ('bindingdb','v4'),
                                ('med_chem_express','v3'),
                                ('selleckchem','v3'),
                                ('cayman','v2'),
                                ],
                        DNChBX_ki=(
                                'duma.default',
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                'chembl.ki',
                                'bindingdb.c50',
                                'bindingdb.ki',
                                ),
                        ),
                ),
        5:dict(
                description='Update MCE & duma with PROTACs',
                **dpimerge_config(
                        match_inputs=[
                                ('chembl','v2'),
                                ('drugbank','v2'),
                                ('duma','v4'),
                                ('ncats','v1'),
                                ('bindingdb','v4'),
                                ('med_chem_express','v3'),
                                ('selleckchem','v3'),
                                ('cayman','v2'),
                                ],
                        DNChBX_ki=(
                                'duma.default',
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                'chembl.ki',
                                'bindingdb.c50',
                                'bindingdb.ki',
                                ),
                        ),
                ),
        4:dict(
                description='clustering experiments',
                **dpimerge_config(
                        match_inputs=[
                                ('chembl','v2'),
                                ('drugbank','v2'),
                                ('duma','v3'),
                                ('ncats','v1'),
                                ('bindingdb','v4'),
                                ('med_chem_express','v2'),
                                ('selleckchem','v3'),
                                ('cayman','v2'),
                                ],
                        DNChBX_ki=(
                                'duma.default.v2', # replicate version error
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                'chembl.ki',
                                'bindingdb.c50',
                                'bindingdb.ki',
                                ),
                        ),
                ),
        3:dict(
                description='refresh duma, fix bdb names',
                **dpimerge_config(
                        match_inputs=[
                                ('chembl','v2'),
                                ('drugbank','v2'),
                                ('duma','v2'),
                                ('ncats','v1'),
                                ('bindingdb','v4'),
                                ('med_chem_express','v2'),
                                ('selleckchem','v2'),
                                ('cayman','v2'),
                                ],
                        DNChBX_ki=(
                                'duma.default',
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                'chembl.ki',
                                'bindingdb.c50',
                                'bindingdb.ki',
                                ),
                        ),
                ),
        2:dict(
                description='refreshed with new collections',
                **dpimerge_config(
                        match_inputs=[
                                ('chembl','v2'),
                                ('drugbank','v2'),
                                ('duma','v1'),
                                ('ncats','v1'),
                                ('bindingdb','v2'),
                                ('med_chem_express','v2'),
                                ('selleckchem','v2'),
                                ('cayman','v2'),
                                ],
                        default=(
                                'drugbank.default',
                                'ncats.default',
                                ),
                        chembl_homologous=(
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                ),
                        DNChB_ki=(
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                'chembl.ki',
                                'bindingdb.c50',
                                'bindingdb.ki',
                                ),
                        DNChBX_ki=(
                                'duma.default',
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                'chembl.ki',
                                'bindingdb.c50',
                                'bindingdb.ki',
                                ),
                        ),
                ),
        1:dict(
                description='legacy data through versioned pipeline',
                **dpimerge_config(
                        match_inputs=[
                                ('chembl','v1'),
                                ('drugbank','v1'),
                                ('duma','v1'),
                                ('ncats','v1'),
                                ('bindingdb','v1'),
                                ('med_chem_express','v1'),
                                ('selleckchem','v1'),
                                ('cayman','v1'),
                                ],
                        default=(
                                'drugbank.default',
                                'ncats.default',
                                ),
                        chembl_homologous=(
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                ),
                        DNChB_ki=(
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                'chembl.ki',
                                'bindingdb.c50',
                                'bindingdb.ki',
                                ),
                        DNChBX_ki=(
                                'dpi.duma.default',
                                'drugbank.default',
                                'ncats.default',
                                'chembl.c50',
                                'chembl.ki',
                                'bindingdb.c50',
                                'bindingdb.ki',
                                ),
                        ),
                ),
        }
