# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0153_auto_20200130_1106'),
        ('ktsearch', '0001_squashed_0011_auto_20191022_1715'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ktresultgroup',
            unique_together=set([('search', 'wsa')]),
        ),
    ]
