# Generated by Django 2.2.16 on 2020-10-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktsearch', '0002_auto_20200130_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ktsearchresult',
            name='ind_val',
            field=models.IntegerField(choices=[(0, 'Unclassified'), (1, 'FDA Approved Treatment'), (2, 'FDA Documented Cause'), (3, 'Clinically used treatment'), (4, 'Clinically indicated cause'), (5, 'Initial Prediction'), (6, 'Candidate Cause'), (7, 'Researched as treatment'), (8, 'Researched as cause'), (9, 'Inactive Prediction'), (10, 'Patent submitted'), (11, 'Preparing patent'), (12, 'Clinically investigated treatment'), (13, 'Hypothesized treatment'), (14, 'Reviewed Prediction'), (15, 'Hit'), (16, 'Phase 1 treatment'), (17, 'Phase 2 treatment'), (18, 'Phase 3 treatment'), (19, 'In Vitro 1'), (20, 'In Vitro 2'), (21, 'In Vivo 1'), (22, 'In Vivo 2'), (23, 'Reviewed As Molecule')]),
        ),
    ]
