# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patsearch', '0001_squashed_0006_merge_20191016_1531'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patentsearchresult',
            unique_together=set([('search', 'patent')]),
        ),
    ]
