# Generated by Django 2.2.10 on 2020-03-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SraRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(max_length=64)),
                ('bioproject', models.CharField(db_index=True, max_length=64)),
                ('biosample', models.CharField(max_length=64)),
                ('accession', models.CharField(max_length=64)),
                ('attrs_json', models.TextField()),
            ],
            options={
                'unique_together': {('experiment', 'bioproject')},
            },
        ),
    ]
