# Generated by Django 2.2.10 on 2020-03-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='srarun',
            name='geo_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
