# Generated by Django 2.2.19 on 2021-03-18 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0172_stagestatuslog'),
        ('ge', '0002_srarun_geo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GESample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrs_json', models.TextField()),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.AeAccession')),
            ],
        ),
    ]
