# Generated by Django 2.2.19 on 2021-03-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0003_gesample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gesample',
            name='accession',
        ),
        migrations.AddField(
            model_name='gesample',
            name='geoID',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
