# Generated by Django 2.2.19 on 2021-04-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0004_auto_20210331_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='GESamples',
            fields=[
                ('geoID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('attrs_json_gz', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='GESample',
        ),
    ]
