license='https://monarchinitiative.org/about/licensing'
credit_list=[
# just human and disease
    dict(
        title="OrphaNet",
        link="http://www.orphadata.org/cgi-bin/index.php",
        abbrv='orphanet'
        ),
    dict(
        title="GWASCatalog",
        link="https://www.ebi.ac.uk/gwas/docs/about",
        abbrv='gwascatalog'
        ),
    dict(
        title="HPO",
        link="https://hpo.jax.org/app/license",
        abbrv='hpoa'
        ),
    dict(
        title="Monarch annotation",
        link=license,
        abbrv='monarch'
        ),
    dict(
        title="OMIA",
        link="https://www.sydney.edu.au/disclaimer.html",
        abbrv='omia'
        ),
    dict(
        title="ClinVar",
        link="https://www.ncbi.nlm.nih.gov/pubmed/29165669",
        abbrv='clinvar.nt'
        ),
# non human DBs
    dict(
        title="IMPC",
        link="https://www.mousephenotype.org/help/non-programmatic-data-access/",
        abbrv='impc'
        ),
    dict(
        title="MMRRC",
        link="https://www.mmrrc.org/about/data_download.php",
        abbrv='mmrrc'
        ),
    dict(
        title="RGD",
        link="https://rgd.mcw.edu/wg/disclaimer/",
        abbrv='rgd'
        ),
    dict(
        title="SGD",
        link="https://sites.google.com/view/yeastgenome-help/about",
        abbrv='sgd'
        ),
    dict(
        title="WormBase",
        link="https://wormbase.org//about/policies#2--10",
        abbrv='wormbase'
        ),
    dict(
        title="ZFinSlim",
        link="https://zfin.atlassian.net/wiki/spaces/general/pages/1942160112/WARRANTY+AND+LIABILITY+DISCLAIMER+OWNERSHIP+AND+LIMITS+ON+USE",
        abbrv='zfinslim'
        ),
    dict(
        title="XenBase",
        link="https://www.xenbase.org/other/static-xenbase/aboutMOD.jsp",
        abbrv='xenbase.nt'
        ),
]

ignore_list=[
# looked and determined we cannot at this time
    dict(
        title="OMIM",
        link="https://www.omim.org/help/agreement",
        abbrv='omim'
        ),
# non human DBs
    dict(
        title="Coriell",
        link="https://catalog.coriell.org/1/About-Us/Legal-Notice",
        abbrv='coriell'
        ),
    dict(
        title="FlyBase",
        link="https://wiki.flybase.org/wiki/FlyBase:About#FlyBase_Copyright",
        abbrv='flybase'
        ),
    dict(
        title="MGI",
        link="http://www.informatics.jax.org/mgihome/other/copyright.shtml",
        abbrv='mgi'
        ),
    dict(
        title="MGIslim",
        link="http://www.informatics.jax.org/mgihome/other/copyright.shtml",
        abbrv='mgislim'
        ),
]

