# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-10 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ctsearch', '0001_initial'), ('ctsearch', '0002_auto_20170908_1511'), ('ctsearch', '0003_auto_20191011_1433'), ('ctsearch', '0003_auto_20191011_1354'), ('ctsearch', '0004_merge_20191016_1531')]

    initial = True

    dependencies = [
        ('browse', '0094_auto_20170814_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtDrugName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=256)),
                ('status', models.IntegerField(choices=[(0, b'Unresolved'), (1, b'Unmatched'), (2, b'Ambiguous'), (3, b'Premarked'), (4, b'Assigned'), (5, b'Rejected')], default=0)),
                ('study_id', models.CharField(blank=True, default=b'', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='CtSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=70)),
                ('config', models.TextField(blank=True, default='')),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.AddField(
            model_name='ctdrugname',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctsearch.CtSearch'),
        ),
        migrations.AlterField(
            model_name='ctdrugname',
            name='status',
            field=models.IntegerField(choices=[(0, b'Unresolved'), (1, b'Unmatched'), (2, b'Ambiguous'), (3, b'Premarked'), (4, b'Assigned'), (5, b'Rejected'), (6, b'Manual')], default=0),
        ),
        migrations.AlterField(
            model_name='ctdrugname',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unresolved'), (1, 'Unmatched'), (2, 'Ambiguous'), (3, 'Premarked'), (4, 'Assigned'), (5, 'Rejected'), (6, 'Manual')], default=0),
        ),
        migrations.AlterField(
            model_name='ctdrugname',
            name='study_id',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='ctdrugname',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unresolved'), (1, 'Unmatched'), (2, 'Ambiguous'), (3, 'Premarked'), (4, 'Assigned'), (5, 'Rejected'), (6, 'Manual')], default=0),
        ),
        migrations.AlterField(
            model_name='ctdrugname',
            name='study_id',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
