# Generated by Django 2.2.10 on 2020-05-12 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('browse', '0164_auto_20200424_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitScoreValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoretype', models.IntegerField(choices=[(0, 'Preclinical Novelty'), (1, 'Commercial Availability'), (2, 'Tolerability'), (3, 'Intellectual Property'), (4, 'Dosing, RoA'), (5, 'Pharmacokinetics'), (6, 'Chemistry'), (7, 'Potency'), (8, 'Selectivity')])),
                ('value', models.FloatField(null=True)),
                ('note', models.TextField(blank=True)),
                ('wsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.WsAnnotation')),
            ],
            options={
                'unique_together': {('wsa', 'scoretype')},
            },
        ),
        migrations.CreateModel(
            name='HitScoreValueLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('note', models.TextField()),
                ('hsv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moldata.HitScoreValue')),
            ],
        ),
    ]
