# Generated by Django 2.2.10 on 2020-05-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0164_auto_20200424_1102'),
        ('moldata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MolSetMoa',
            fields=[
                ('ds', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='browse.DrugSet')),
                ('proteins', models.ManyToManyField(to='browse.Protein')),
            ],
        ),
    ]
