# Generated by Django 2.2.10 on 2020-07-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moldata', '0002_molsetmoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitscorevalue',
            name='scoretype',
            field=models.IntegerField(choices=[(0, 'Preclinical Novelty'), (1, 'Commercial Availability'), (2, 'Tolerability'), (3, 'Intellectual Property'), (4, 'Dosing, RoA'), (5, 'Pharmacokinetics'), (6, 'Chemistry'), (7, 'Potency'), (8, 'Selectivity'), (9, 'Hitsel Note')]),
        ),
    ]
