# Generated by Django 2.2.10 on 2020-08-05 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200625_1100'),
        ('moldata', '0003_auto_20200727_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='molsetmoa',
            name='hitsel_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hitsel_note', to='notes.Note'),
        ),
        migrations.AddField(
            model_name='molsetmoa',
            name='preclin_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preclin_note', to='notes.Note'),
        ),
    ]
