# Generated by Django 2.2.24 on 2022-01-07 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0178_workflowjob'),
        ('moldata', '0004_auto_20200805_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTrialAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph2_status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Failed'), (2, 'Ongoing'), (3, 'Passed')])),
                ('ph2_url', models.TextField(blank=True)),
                ('ph3_status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Failed'), (2, 'Ongoing'), (3, 'Passed')])),
                ('ph3_url', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=50)),
                ('wsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.WsAnnotation')),
            ],
        ),
    ]
