# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-10 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('flagging', '0001_initial'), ('flagging', '0002_auto_20180411_1602'), ('flagging', '0003_auto_20191011_1433'), ('flagging', '0003_auto_20191011_1354'), ('flagging', '0004_merge_20191016_1531')]

    initial = True

    dependencies = [
        ('browse', '0088_auto_20170202_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('detail', models.CharField(blank=True, default=b'', max_length=256)),
                ('href', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='FlagSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('settings', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.AddField(
            model_name='flag',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flagging.FlagSet'),
        ),
        migrations.AddField(
            model_name='flag',
            name='wsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.WsAnnotation'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='href',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='flag',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='flag',
            name='href',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='flag',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='flag',
            name='href',
            field=models.TextField(blank=True, default=''),
        ),
    ]
