# Generated by Django 2.2.10 on 2020-07-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('browse', '0165_drugsetchange'),
        ('drugs', '0007_auto_20200531_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=70)),
                ('operation', models.CharField(max_length=70)),
                ('succeeded', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.Collection')),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
    ]
