# Generated by Django 2.2.10 on 2020-07-07 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0165_drugsetchange'),
        ('wsmgr', '0002_auto_20200707_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='importaudit',
            name='wsa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='browse.WsAnnotation'),
        ),
    ]
