from django.conf.urls import include, re_path

from . import views

urlpatterns = [
    re_path(r'^ws_cmp/', views.ws_cmp, name='nav_ws_cmp'),
    re_path(r'^([0-9]+)/url_test/', views.url_test, name='nav_url_test'),
    re_path(r'^([0-9]+)/textdiff/', views.textdiff, name='nav_textdiff'),
    re_path(r'^([0-9]+)/plot/', views.plot, name='nav_plot'),
    re_path(r'^(?P<ws_id>[0-9]+)/col2/', views.Col2View.as_view(), name='nav_col2'),
    re_path(r'^(?P<ws_id>[0-9]+)/impstat/', views.ImpStatView.as_view(), name='nav_impstat'),
    re_path(r'^(?P<ws_id>[0-9]+)/ds/', views.dsView.as_view(), name='nav_ds'),
    re_path(r'^(?P<ws_id>[0-9]+)/ds_dpi_cmp/',
        views.dsDpiCmpView.as_view(),
        name='nav_ds_dpi_cmp'),
    re_path(r'^([0-9]+)/ps_cmp/', views.ps_cmp, name='nav_ps_cmp'),
    re_path(r'^([0-9]+)/ps/', views.ps, name='nav_ps'),
    re_path(r'^(?P<ws_id>[0-9]+)/split_align/',
                    views.SplitAlignView.as_view(),
                    name='nav_split_align',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/disease_sum/',
                    views.DiseaseSumView.as_view(),
                    name='nav_disease_sum',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/disease_names/',
                    views.DiseaseNamesView.as_view(),
                    name='nav_disease_names',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/disease_name_edit/(?P<disease_vocab>[A-Za-z_0-9]+)/',
                    views.DiseaseNameEditView.as_view(),
                    name='nav_disease_name_edit',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/ontobrowse/(?P<disease_vocab>[A-Za-z_0-9]+)/',
                    views.OntoBrowseView.as_view(),
                    name='nav_ontobrowse',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/ontolist/(?P<disease_vocab>[A-Za-z_0-9]+)/',
                    views.OntoListView.as_view(),
                    name='nav_ontolist',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/kt_clusters/',
                    views.KtClustersView.as_view(),
                    name='nav_kt_clusters',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/rvw_clusters/',
                    views.RvwClustersView.as_view(),
                    name='nav_rvw_clusters',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/score_corr/',
                    views.ScoreCorrView.as_view(),
                    name='nav_score_corr',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/score_metrics/',
                    views.ScoreMetricsView.as_view(),
                    name='nav_score_metrics',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/scoreboard/',
                    views.ScoreboardView.as_view(),
                    name='nav_scoreboard',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/xws_cmp/',
                    views.XwsCmpView.as_view(),
                    name='nav_xws_cmp',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/scoreplot/(?P<dtc>[a-z]+)/',
                    views.ScorePlotView.as_view(),
                    name='nav_scoreplot',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/scoreplot_simple/(?P<dtc>[a-z]+)/',
                    views.ScorePlotSimpleView.as_view(),
                    name='nav_scoreplot_simple',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/score_pi_overlap/(?P<dtc>[a-z]+)/',
                    views.ScorePIOverlap.as_view(),
                    name='nav_score_pi_overlap',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/score_cmp/(?P<dtc>[a-z]+)/',
                    views.ScoreCmpView.as_view(),
                    name='nav_score_cmp',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/score_select/(?P<jobname>[a-z_0-9]+)/',
                    views.ScoreSelectView.as_view(),
                    name='nav_score_select',
                    ),
    re_path(r'^([0-9]+)/progress/([0-9]+)/', views.progress, name='nav_progress'),
    re_path(r'^([0-9]+)/adr_info/([0-9]+)/', views.adr_info, name='nav_adr_info'),
    re_path(r'^(?P<ws_id>[0-9]+)/adrs/(?P<wsa_id>[0-9]+)/', views.AdrsView.as_view(), name='nav_adrs'),
    # The following need to support upper case letters in jobnames to handle
    # workflows
    re_path(r'^(?P<ws_id>[0-9]+)/job_start/(?P<jobname>[A-Za-z_0-9]+)/(?P<copy_job>[0-9]+)/',
                    views.JobStartView.as_view(),
                    name='nav_job_start',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/job_start/(?P<jobname>[A-Za-z_0-9]+)/',
                    views.JobStartView.as_view(),
                    name='nav_job_start',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/refresh_qc/',
                    views.RefreshQCView.as_view(),
                    name='nav_refresh_qc',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/refresh_qc_plots/',
                    views.RefreshQCPlotsView.as_view(),
                    name='nav_refresh_qc_plots',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/scoreset_list/',
                    views.ScoresetListView.as_view(),
                    name='nav_scoreset_list',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/scoreset/(?P<scoreset_id>[0-9]+)/',
                    views.ScoresetView.as_view(),
                    name='nav_scoreset',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/scoreset_edit/(?P<scoreset_id>[0-9]+)/',
                    views.ScoresetEditView.as_view(),
                    name='nav_scoreset_edit',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/add_to_scoreset/(?P<job_id>[0-9]+)/',
                    views.AddToScoresetView.as_view(),
                    name='nav_add_to_scoreset',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/prescreen_list/',
                    views.PrescreenListView.as_view(),
                    name='nav_prescreen_list',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/prescreen_edit/(?P<prescreen_id>[0-9]+)/',
                    views.PrescreenEditView.as_view(),
                    name='nav_prescreen_edit',
                    ),
    re_path(r'^([0-9]+)/matching/([0-9]+)/', views.matching, name='nav_matching'),
    re_path(r'^(?P<ws_id>[0-9]+)/score_grid/',
                    views.ScoreGrid.as_view(),
                    name='nav_score_grid',
                    ),
    re_path(r'^(?P<ws_id>[0-9]+)/workflow_timeline/(?P<job_id>[0-9]+)/',
                    views.WorkflowTimelineView.as_view(),
                    name='nav_workflow_timeline',
                    ),
]
