# Generated by Django 2.2.18 on 2021-02-09 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('browse', '0172_stagestatuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDpi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('base_dpi', models.CharField(max_length=256)),
                ('prot_set', models.CharField(max_length=256)),
                ('mode', models.IntegerField(choices=[(0, 'Subtract'), (1, 'Exclusive')])),
                ('descr', models.TextField()),
                ('deprecated', models.BooleanField(default=False)),
                ('uid', models.CharField(max_length=256)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=256)),
                ('protset_prots', models.IntegerField()),
                ('base_prots', models.IntegerField()),
                ('final_prots', models.IntegerField()),
                ('base_molecules', models.IntegerField()),
                ('final_molecules', models.IntegerField()),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
    ]
