# Generated by Django 2.2.19 on 2021-03-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='customdpi',
            index_together={('uid',)},
        ),
    ]
