# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-10 22:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('browse', '0001_initial'), ('browse', '0002_auto_20140821_1612'), ('browse', '0003_auto_20140822_0953'), ('browse', '0004_remove_candidate_label'), ('browse', '0005_druginfo_indication'), ('browse', '0006_druginfo_indication_href'), ('browse', '0007_workspace'), ('browse', '0008_tissue'), ('browse', '0009_samples'), ('browse', '0010_auto_20140909_1522'), ('browse', '0011_significantprotein'), ('browse', '0012_wsannotations'), ('browse', '0013_wsannotations_indication_href'), ('browse', '0014_auto_20140914_2102'), ('browse', '0015_auto_20140915_2107'), ('browse', '0016_candidate_drug_ws'), ('browse', '0017_auto_20140916_0845'), ('browse', '0018_remove_path_geneid'), ('browse', '0019_auto_20140916_2031'), ('browse', '0020_remove_candidate_drugid'), ('browse', '0021_auto_20141001_1010'), ('browse', '0022_auto_20141121_2223'), ('browse', '0023_remove_tissue_status'), ('browse', '0024_tissue_source'), ('browse', '0025_auto_20141212_1712'), ('browse', '0026_wsannotation_patent_review'), ('browse', '0027_patent'), ('browse', '0028_auto_20141217_0931'), ('browse', '0029_druginfo_note'), ('browse', '0030_patent_note'), ('browse', '0031_auto_20141217_2242'), ('browse', '0032_remove_patent_scope'), ('browse', '0033_candidate_run'), ('browse', '0034_wsannotation_study_note'), ('browse', '0035_auto_20150316_2005'), ('browse', '0036_druginfo_hide'), ('browse', '0037_auto_20150317_1907'), ('browse', '0038_wsannotation_agent'), ('browse', '0039_remove_patent_synth_for'), ('browse', '0040_patent_synth_for'), ('browse', '0041_remove_patent_drugs'), ('browse', '0042_patent_drugs'), ('browse', '0043_auto_20150526_1857'), ('browse', '0044_auto_20150609_1126'), ('browse', '0045_sample_attributes'), ('browse', '0046_auto_20150707_1649'), ('browse', '0047_tissue_note'), ('browse', '0048_auto_20150923_1749'), ('browse', '0049_wsannotation_doc_href'), ('browse', '0050_candidate_path_key'), ('browse', '0051_auto_20160111_1528'), ('browse', '0052_auto_20160120_1003'), ('browse', '0053_auto_20160120_1919'), ('browse', '0054_drugset'), ('browse', '0055_election_vote'), ('browse', '0056_auto_20160205_0945'), ('browse', '0057_workspace_active'), ('browse', '0058_runset'), ('browse', '0059_runset_ws'), ('browse', '0060_auto_20160426_1133'), ('browse', '0061_tissue_invalid'), ('browse', '0062_demerit'), ('browse', '0063_wsannotation_demerit_list'), ('browse', '0064_dispositionaudit'), ('browse', '0065_auto_20160503_1825'), ('browse', '0066_scoreboard'), ('browse', '0067_auto_20160525_0921'), ('browse', '0068_significantprotein_fold_change'), ('browse', '0069_dispositionaudit_indication_href'), ('browse', '0070_protein_protset'), ('browse', '0071_auto_20160627_1850'), ('browse', '0072_aeaccession_desc'), ('browse', '0073_aesearch_mode'), ('browse', '0074_auto_20160920_1611'), ('browse', '0075_auto_20160920_1800'), ('browse', '0076_tissue_cc_selected'), ('browse', '0077_auto_20161004_1109'), ('browse', '0078_auto_20161024_1518'), ('browse', '0079_workspace_cross_compare'), ('browse', '0080_auto_20161201_1335'), ('browse', '0081_auto_20161212_1703'), ('browse', '0081_auto_20161208_1240'), ('browse', '0082_merge'), ('browse', '0083_useraccess'), ('browse', '0084_auto_20170116_1653'), ('browse', '0085_proteinattributetype_pathway'), ('browse', '0086_auto_20170117_0859'), ('browse', '0087_auto_20170119_0935'), ('browse', '0088_auto_20170202_0934'), ('browse', '0089_gwasdataset'), ('browse', '0090_auto_20170510_1832'), ('browse', '0091_gwasfilter_rejected'), ('browse', '0092_auto_20170811_0947'), ('browse', '0093_ctdrugname_study_id'), ('browse', '0094_auto_20170814_0843'), ('browse', '0095_auto_20170823_0933'), ('browse', '0096_workspace_eval_drugset'), ('browse', '0097_auto_20170831_0859'), ('browse', '0098_auto_20170906_1403'), ('browse', '0099_wsannotation_invalid'), ('browse', '0100_aesearch_nonhumans'), ('browse', '0101_ktaudit'), ('browse', '0102_auto_20171122_1529'), ('browse', '0103_aeaccession_pub_ref'), ('browse', '0104_diseasedefault'), ('browse', '0105_tissueset_mirna'), ('browse', '0106_auto_20180201_1336'), ('browse', '0107_tissue_ignore_missing'), ('browse', '0108_auto_20180328_1504'), ('browse', '0109_auto_20180328_1509'), ('browse', '0110_auto_20180413_1327'), ('browse', '0111_auto_20180413_1331'), ('browse', '0112_workspace_disease_note'), ('browse', '0113_scoreboard_note'), ('browse', '0114_auto_20180516_1111'), ('browse', '0115_wsannotation_review_code'), ('browse', '0116_scoreboard_prescreen_extra_enables'), ('browse', '0117_runset_wf_job'), ('browse', '0118_scoreset_scoresetjob'), ('browse', '0119_prescreen'), ('browse', '0120_auto_20190204_1213'), ('browse', '0121_auto_20190209_1521'), ('browse', '0122_election_flavor'), ('browse', '0123_auto_20190319_1102'), ('browse', '0124_auto_20190508_1000'), ('browse', '0125_drugsplit'), ('browse', '0126_auto_20190701_1433'), ('browse', '0127_auto_20190701_1437'), ('browse', '0125_auto_20190628_1025'), ('browse', '0128_merge'), ('browse', '0129_targetannotation_targetreview'), ('browse', '0130_auto_20190728_2059'), ('browse', '0131_auto_20190729_1606'), ('browse', '0132_workspace_unwanted_ps_default'), ('browse', '0133_workspace_nonnovel_ps_default'), ('browse', '0134_versiondefault_versiondefaultaudit'), ('browse', '0135_auto_20190919_1114'), ('browse', '0136_auto_20190919_1151'), ('browse', '0135_stagestatus'), ('browse', '0137_merge_20190924_2341'), ('browse', '0138_auto_20190926_1451'), ('browse', '0139_auto_20191004_1523'), ('browse', '0139_auto_20191004_1137'), ('browse', '0140_merge_20191008_1725'), ('browse', '0141_auto_20191011_1433'), ('browse', '0141_auto_20191011_1354'), ('browse', '0142_merge_20191016_1531'), ('browse', '0142_auto_20191017_0853'), ('browse', '0143_merge_20191022_1715'), ('browse', '0144_auto_20191022_1715')]

    initial = True

    dependencies = [
        ('drugs', '0006_remove_drug_name'),
        ('runner', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
        ('notes', '0002_auto_20160204_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('geoID', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, b'Fetching'), (1, b'Fetch Failed'), (2, b'Fetch Succeeded'), (3, b'SAM Running'), (4, b'SAM Failed'), (5, b'SAM Succeeded')])),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=150)),
                ('primary_factor', models.CharField(max_length=256)),
                ('secondary_factor', models.CharField(max_length=256)),
                ('classification', models.IntegerField(choices=[(0, 'Ignore'), (1, 'Case'), (2, 'Control')])),
                ('tissue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Tissue')),
                ('attributes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='WsAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication', models.IntegerField(choices=[(0, b'Unclassified'), (1, b'FDA Approved Treatment'), (2, b'FDA Documented Cause'), (3, b'Clinically used treatment'), (4, b'Clinically indicated cause'), (5, b'Candidate Treatment'), (6, b'Candidate Cause'), (7, b'Reseached as treatment'), (8, b'Researched as cause'), (9, b'Inactive Candidate'), (10, b'Patent submitted')], default=0)),
                ('indication_href', models.CharField(blank=True, default=b'', max_length=1024)),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
                ('ml_probability', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('marked_because', models.CharField(blank=True, default=b'', max_length=1024)),
                ('marked_by', models.CharField(blank=True, default=b'', max_length=50)),
                ('marked_on', models.DateTimeField(blank=True, null=True)),
                ('indication_protection', models.IntegerField(choices=[(0, b'Not Screened'), (1, b'No Patent Found'), (2, b'Weak Protection'), (3, b'Protected'), (4, b'Strong Protection')], default=0)),
                ('study_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
                ('ml_other_probability', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('ml_path_probability', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('ml_struct_probability', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.Drug')),
                ('doc_href', models.CharField(blank=True, default=b'', max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='tissue',
            name='status',
        ),
        migrations.AddField(
            model_name='tissue',
            name='source',
            field=models.CharField(default='geo', max_length=20),
        ),
        migrations.AddField(
            model_name='tissue',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note'),
        ),
        migrations.AlterField(
            model_name='tissue',
            name='geoID',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='TissueSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('case_label', models.CharField(default='Case', max_length=100)),
                ('control_label', models.CharField(default='Control', max_length=100)),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
                ('miRNA', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='tissue',
            name='tissue_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='browse.TissueSet'),
        ),
        migrations.CreateModel(
            name='DrugSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('drugs', models.ManyToManyField(to='browse.WsAnnotation')),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.DateTimeField()),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=50)),
                ('recommended', models.NullBooleanField()),
                ('disabled', models.BooleanField(default=False)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.WsAnnotation')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Election')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
            ],
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='indication',
            field=models.IntegerField(choices=[(0, b'Unclassified'), (1, b'FDA Approved Treatment'), (2, b'FDA Documented Cause'), (3, b'Clinically used treatment'), (4, b'Clinically indicated cause'), (5, b'Candidate Treatment'), (6, b'Candidate Cause'), (7, b'Reseached as treatment'), (8, b'Researched as cause'), (9, b'Inactive Candidate'), (10, b'Patent submitted'), (11, b'Preparing patent')], default=0),
        ),
        migrations.AddField(
            model_name='workspace',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RunSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=70)),
                ('job_list', models.CharField(max_length=512)),
                ('job_type', models.CharField(max_length=70)),
                ('desc', models.CharField(max_length=256)),
                ('variable', models.CharField(max_length=70)),
                ('score_idx', models.IntegerField()),
                ('ws', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='RunSetJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('job_type', models.TextField()),
                ('runset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.RunSet')),
            ],
        ),
        migrations.AddField(
            model_name='runset',
            name='common_config',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='runset',
            name='job_list',
        ),
        migrations.RemoveField(
            model_name='runset',
            name='variable',
        ),
        migrations.AddField(
            model_name='tissue',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Demerit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='wsannotation',
            name='demerit_list',
            field=models.CharField(blank=True, default=b'', max_length=1024),
        ),
        migrations.CreateModel(
            name='DispositionAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='', max_length=50)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=1024)),
                ('indication', models.IntegerField()),
                ('demerit_list', models.CharField(blank=True, default='', max_length=1024)),
                ('wsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.WsAnnotation')),
                ('indication_href', models.CharField(blank=True, default='', max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='indication',
            field=models.IntegerField(choices=[(0, b'Unclassified'), (1, b'FDA Approved Treatment'), (2, b'FDA Documented Cause'), (3, b'Clinically used treatment'), (4, b'Clinically indicated cause'), (5, b'Candidate Treatment'), (6, b'Candidate Cause'), (7, b'Reseached as treatment'), (8, b'Researched as cause'), (9, b'Inactive Candidate'), (10, b'Patent submitted'), (11, b'Preparing patent'), (12, b'Clinically investigated treatment'), (13, b'Hypothesized treatment')], default=0),
        ),
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=256)),
                ('score_list', models.TextField()),
                ('enables', models.TextField()),
                ('sort', models.CharField(blank=True, default=b'', max_length=512)),
                ('filters', models.CharField(blank=True, default=b'', max_length=512)),
                ('preselecting', models.BooleanField(default=False)),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='indication',
            field=models.IntegerField(choices=[(0, b'Unclassified'), (1, b'FDA Approved Treatment'), (2, b'FDA Documented Cause'), (3, b'Clinically used treatment'), (4, b'Clinically indicated cause'), (5, b'Candidate Treatment'), (6, b'Candidate Cause'), (7, b'Researched as treatment'), (8, b'Researched as cause'), (9, b'Inactive Candidate'), (10, b'Patent submitted'), (11, b'Preparing patent'), (12, b'Clinically investigated treatment'), (13, b'Hypothesized treatment')], default=0),
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot', models.CharField(max_length=56)),
                ('gene', models.CharField(default=b'', max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='ProtSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('proteins', models.ManyToManyField(to='browse.Protein')),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='AeAccession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoID', models.CharField(max_length=256)),
                ('rejected', models.CharField(blank=True, default=b'', max_length=1024)),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='AeScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.AeAccession')),
            ],
        ),
        migrations.CreateModel(
            name='AeSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=256)),
                ('when', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='aescore',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.AeSearch'),
        ),
        migrations.AddField(
            model_name='aesearch',
            name='scores',
            field=models.ManyToManyField(through='browse.AeScore', to='browse.AeAccession'),
        ),
        migrations.AddField(
            model_name='aesearch',
            name='ws',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace'),
        ),
        migrations.AddField(
            model_name='aeaccession',
            name='desc',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='aesearch',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Case/Control'), (1, 'Treatment/Response')], default=0),
        ),
        migrations.CreateModel(
            name='AeDisposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(choices=[(0, 'Case/Control'), (1, 'Treatment/Response')], default=0)),
                ('rejected', models.CharField(max_length=1024)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.AeAccession')),
            ],
        ),
        migrations.RenameField(
            model_name='aeaccession',
            old_name='rejected',
            new_name='old_rejected',
        ),
        migrations.AddField(
            model_name='aeaccession',
            name='src_default',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aeaccession',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tissue',
            name='cc_selected',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='workspace',
            name='cross_compare',
            field=models.NullBooleanField(),
        ),
        migrations.RemoveField(
            model_name='aeaccession',
            name='old_rejected',
        ),
        migrations.AddField(
            model_name='tissue',
            name='fallback_reason',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='runset',
            name='job_type',
            field=models.CharField(blank=True, default=b'', max_length=70),
        ),
        migrations.AlterField(
            model_name='runset',
            name='score_idx',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='ProteinAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinAttributeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('pathway_group', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='uniprot_kb',
            field=models.CharField(default='', max_length=56),
        ),
        migrations.AddField(
            model_name='proteinattribute',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.ProteinAttributeType'),
        ),
        migrations.AddField(
            model_name='proteinattribute',
            name='prot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Protein'),
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=70)),
                ('access', models.CharField(max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tissue',
            name='ev_cutoff',
            field=models.FloatField(default=0.95),
        ),
        migrations.AddField(
            model_name='tissue',
            name='fc_cutoff',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='GwasDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenotype', models.CharField(max_length=1024)),
                ('pubmed_id', models.IntegerField()),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='GwasFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubmed_id', models.IntegerField()),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
                ('rejected', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='gwasdataset',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note'),
        ),
        migrations.AddField(
            model_name='gwasdataset',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='eval_drugset',
            field=models.CharField(default=b'kts', max_length=256),
        ),
        migrations.AddField(
            model_name='tissue',
            name='cutoff_job_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tissue',
            name='over_proteins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tissue',
            name='sig_result_job_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tissue',
            name='total_proteins',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='wsannotation',
            name='ml_other_probability',
        ),
        migrations.RemoveField(
            model_name='wsannotation',
            name='ml_path_probability',
        ),
        migrations.RemoveField(
            model_name='wsannotation',
            name='ml_probability',
        ),
        migrations.RemoveField(
            model_name='wsannotation',
            name='ml_struct_probability',
        ),
        migrations.AddField(
            model_name='wsannotation',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aesearch',
            name='nonhumans',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='KtAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('key', models.CharField(blank=True, default='', max_length=250)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('new_matches', models.IntegerField()),
                ('old_matches', models.IntegerField()),
                ('unmatched', models.IntegerField()),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.AddField(
            model_name='aeaccession',
            name='pub_ref',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='DiseaseDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(blank=True, default='', max_length=100)),
                ('value', models.TextField(blank=True, default='')),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tissue',
            name='ignore_missing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='dpi_default',
            field=models.CharField(blank=True, default=b'', max_length=256),
        ),
        migrations.AddField(
            model_name='workspace',
            name='dpi_thresh_default',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='ppi_default',
            field=models.CharField(blank=True, default=b'', max_length=256),
        ),
        migrations.AddField(
            model_name='workspace',
            name='ppi_thresh_default',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='disease_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note'),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note'),
        ),
        migrations.AddField(
            model_name='wsannotation',
            name='review_code',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='prescreen_extra_enables',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='runset',
            name='wf_job',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='ScoreSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=70)),
                ('desc', models.TextField()),
                ('wf_job', models.IntegerField(null=True)),
                ('sort_score', models.CharField(blank=True, default=b'', max_length=70)),
                ('saved_filters', models.TextField(blank=True, default=b'')),
                ('migrated_from', models.CharField(blank=True, default=b'', max_length=70)),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSetJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('job_type', models.TextField()),
                ('label', models.TextField(blank=True, default='')),
                ('enables', models.TextField(blank=True, default='')),
                ('scoreset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.ScoreSet')),
            ],
        ),
        migrations.CreateModel(
            name='Prescreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=256)),
                ('primary_score', models.CharField(max_length=512)),
                ('filters', models.CharField(blank=True, default='', max_length=512)),
                ('extra_scores', models.TextField(blank=True, default='')),
                ('old_prescreen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='browse.Scoreboard')),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.AlterField(
            model_name='scoreset',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='election',
            name='flavor',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='indication',
            field=models.IntegerField(choices=[(0, b'Unclassified'), (1, b'FDA Approved Treatment'), (2, b'FDA Documented Cause'), (3, b'Clinically used treatment'), (4, b'Clinically indicated cause'), (5, b'Candidate Treatment'), (6, b'Candidate Cause'), (7, b'Researched as treatment'), (8, b'Researched as cause'), (9, b'Inactive Candidate'), (10, b'Patent submitted'), (11, b'Preparing patent'), (12, b'Clinically investigated treatment'), (13, b'Hypothesized treatment'), (14, b'Reviewed Candidate'), (15, b'Preclinical Candidate')], default=0),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='indication',
            field=models.IntegerField(choices=[(0, b'Unclassified'), (1, b'FDA Approved Treatment'), (2, b'FDA Documented Cause'), (3, b'Clinically used treatment'), (4, b'Clinically indicated cause'), (5, b'Candidate Treatment'), (6, b'Candidate Cause'), (7, b'Researched as treatment'), (8, b'Researched as cause'), (9, b'Inactive Candidate'), (10, b'Patent submitted'), (11, b'Preparing patent'), (12, b'Clinically investigated treatment'), (13, b'Hypothesized treatment'), (14, b'Reviewed Candidate'), (15, b'Preclinical Candidate'), (16, b'Phase 1 treatment'), (17, b'Phase 2 treatment'), (18, b'Phase 3 treatment')], default=0),
        ),
        migrations.CreateModel(
            name='DrugSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('manual_edits', models.BooleanField(default=False)),
                ('drugs', models.ManyToManyField(to='browse.WsAnnotation')),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='protein',
            index_together=set([('gene',), ('uniprot',)]),
        ),
        migrations.AlterIndexTogether(
            name='proteinattribute',
            index_together=set([('val',)]),
        ),
        migrations.CreateModel(
            name='TargetAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot', models.CharField(max_length=56)),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='TargetReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=70)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.TargetAnnotation')),
            ],
        ),
        migrations.RenameField(
            model_name='targetannotation',
            old_name='uniprot',
            new_name='uniprot',
        ),
        migrations.AddField(
            model_name='workspace',
            name='unwanted_ps_default',
            field=models.CharField(blank=True, default=b'', max_length=256),
        ),
        migrations.AddField(
            model_name='workspace',
            name='nonnovel_ps_default',
            field=models.CharField(blank=True, default=b'', max_length=256),
        ),
        migrations.CreateModel(
            name='VersionDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_class', models.CharField(max_length=100)),
                ('choice', models.CharField(max_length=100)),
                ('ws', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='VersionDefaultAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_class', models.CharField(max_length=100)),
                ('choice', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('ws', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='indication',
            field=models.IntegerField(choices=[(0, b'Unclassified'), (1, b'FDA Approved Treatment'), (2, b'FDA Documented Cause'), (3, b'Clinically used treatment'), (4, b'Clinically indicated cause'), (5, b'Candidate Treatment'), (6, b'Candidate Cause'), (7, b'Researched as treatment'), (8, b'Researched as cause'), (9, b'Inactive Candidate'), (10, b'Patent submitted'), (11, b'Preparing patent'), (12, b'Clinically investigated treatment'), (13, b'Hypothesized treatment'), (14, b'Reviewed Candidate'), (15, b'Preclinical Candidate'), (16, b'Phase 1 treatment'), (17, b'Phase 2 treatment'), (18, b'Phase 3 treatment'), (19, b'In Vitro 1'), (20, b'In Vitro 2'), (21, b'In Vivo 1'), (22, b'In Vivo 2')], default=0),
        ),
        migrations.AlterIndexTogether(
            name='dispositionaudit',
            index_together=set([('indication',)]),
        ),
        migrations.CreateModel(
            name='StageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=128)),
                ('status', models.IntegerField(choices=[(0, 'None'), (1, 'Active'), (2, 'Complete')], default=0)),
                ('changed_on', models.DateTimeField(auto_now=True)),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Workspace')),
            ],
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='demerit_list',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='doc_href',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterIndexTogether(
            name='wsannotation',
            index_together=set([('ws', 'indication'), ('ws', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='gwasdataset',
            name='pubmed_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AddField(
            model_name='workspace',
            name='short_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='aeaccession',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='protein',
            name='gene',
            field=models.CharField(default='', max_length=56),
        ),
        migrations.AlterField(
            model_name='runset',
            name='job_type',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='filters',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='prescreen_extra_enables',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='sort',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='scoreset',
            name='migrated_from',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='scoreset',
            name='saved_filters',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scoreset',
            name='sort_score',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='dpi_default',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='eval_drugset',
            field=models.CharField(default='kts', max_length=256),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='nonnovel_ps_default',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='ppi_default',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='unwanted_ps_default',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='indication',
            field=models.IntegerField(choices=[(0, 'Unclassified'), (1, 'FDA Approved Treatment'), (2, 'FDA Documented Cause'), (3, 'Clinically used treatment'), (4, 'Clinically indicated cause'), (5, 'Candidate Treatment'), (6, 'Candidate Cause'), (7, 'Researched as treatment'), (8, 'Researched as cause'), (9, 'Inactive Candidate'), (10, 'Patent submitted'), (11, 'Preparing patent'), (12, 'Clinically investigated treatment'), (13, 'Hypothesized treatment'), (14, 'Reviewed Candidate'), (15, 'Preclinical Candidate'), (16, 'Phase 1 treatment'), (17, 'Phase 2 treatment'), (18, 'Phase 3 treatment'), (19, 'In Vitro 1'), (20, 'In Vitro 2'), (21, 'In Vivo 1'), (22, 'In Vivo 2')], default=0),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='indication_href',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='indication_protection',
            field=models.IntegerField(choices=[(0, 'Not Screened'), (1, 'No Patent Found'), (2, 'Weak Protection'), (3, 'Protected'), (4, 'Strong Protection')], default=0),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='marked_because',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='marked_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='review_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='aeaccession',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='protein',
            name='gene',
            field=models.CharField(default='', max_length=56),
        ),
        migrations.AlterField(
            model_name='runset',
            name='job_type',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='filters',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='prescreen_extra_enables',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='sort',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='scoreset',
            name='migrated_from',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='scoreset',
            name='saved_filters',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scoreset',
            name='sort_score',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='dpi_default',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='eval_drugset',
            field=models.CharField(default='kts', max_length=256),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='nonnovel_ps_default',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='ppi_default',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='unwanted_ps_default',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='demerit_list',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='doc_href',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='indication',
            field=models.IntegerField(choices=[(0, 'Unclassified'), (1, 'FDA Approved Treatment'), (2, 'FDA Documented Cause'), (3, 'Clinically used treatment'), (4, 'Clinically indicated cause'), (5, 'Candidate Treatment'), (6, 'Candidate Cause'), (7, 'Researched as treatment'), (8, 'Researched as cause'), (9, 'Inactive Candidate'), (10, 'Patent submitted'), (11, 'Preparing patent'), (12, 'Clinically investigated treatment'), (13, 'Hypothesized treatment'), (14, 'Reviewed Candidate'), (15, 'Preclinical Candidate'), (16, 'Phase 1 treatment'), (17, 'Phase 2 treatment'), (18, 'Phase 3 treatment'), (19, 'In Vitro 1'), (20, 'In Vitro 2'), (21, 'In Vivo 1'), (22, 'In Vivo 2')], default=0),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='indication_href',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='indication_protection',
            field=models.IntegerField(choices=[(0, 'Not Screened'), (1, 'No Patent Found'), (2, 'Weak Protection'), (3, 'Protected'), (4, 'Strong Protection')], default=0),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='marked_because',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='marked_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='review_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterIndexTogether(
            name='stagestatus',
            index_together=set([('stage_name',)]),
        ),
        migrations.AlterField(
            model_name='wsannotation',
            name='indication',
            field=models.IntegerField(choices=[(0, 'Unclassified'), (1, 'FDA Approved Treatment'), (2, 'FDA Documented Cause'), (3, 'Clinically used treatment'), (4, 'Clinically indicated cause'), (5, 'Initial Prediction'), (6, 'Candidate Cause'), (7, 'Researched as treatment'), (8, 'Researched as cause'), (9, 'Inactive Prediction'), (10, 'Patent submitted'), (11, 'Preparing patent'), (12, 'Clinically investigated treatment'), (13, 'Hypothesized treatment'), (14, 'Reviewed Prediction'), (15, 'Hit'), (16, 'Phase 1 treatment'), (17, 'Phase 2 treatment'), (18, 'Phase 3 treatment'), (19, 'In Vitro 1'), (20, 'In Vitro 2'), (21, 'In Vivo 1'), (22, 'In Vivo 2')], default=0),
        ),
    ]
