# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-19 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_squashed_0144_auto_20191022_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='demerit',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Review'), (1, 'Preclinical')], default=0),
        ),
    ]
