# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-20 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0145_demerit_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositionaudit',
            name='from_prescreen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='browse.Prescreen'),
        ),
        migrations.AddField(
            model_name='wsannotation',
            name='marked_prescreen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='browse.Prescreen'),
        ),
    ]
