# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-03 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0147_auto_20191120_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositionaudit',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
