# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-10 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0148_dispositionaudit_ignore'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsannotation',
            name='replaced_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='browse.WsAnnotation'),
        ),
    ]
