# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-27 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0151_auto_20200120_1038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='targetannotation',
            unique_together=set([('ws', 'uniprot')]),
        ),
    ]
