# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('browse', '0152_auto_20200127_1249'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diseasedefault',
            unique_together=set([('ws', 'vocab')]),
        ),
        migrations.AlterUniqueTogether(
            name='gwasfilter',
            unique_together=set([('ws', 'pubmed_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='proteinattributetype',
            unique_together=set([('name', 'pathway_group')]),
        ),
        migrations.AlterUniqueTogether(
            name='stagestatus',
            unique_together=set([('stage_name', 'ws')]),
        ),
        migrations.AlterUniqueTogether(
            name='targetreview',
            unique_together=set([('user', 'target')]),
        ),
        migrations.AlterUniqueTogether(
            name='useraccess',
            unique_together=set([('user', 'host', 'access')]),
        ),
        migrations.AlterUniqueTogether(
            name='versiondefault',
            unique_together=set([('ws', 'file_class')]),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('election', 'reviewer', 'drug')]),
        ),
    ]
