# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0152_auto_20200127_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsannotation',
            name='replacements',
            field=models.ManyToManyField(related_name='wsa_replacements', to='browse.WsAnnotation'),
        ),
    ]
