# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 20:35
from __future__ import unicode_literals

from django.db import migrations

def copy_replacements(apps, schema_editor):
    WsAnnotation = apps.get_model('browse', 'WsAnnotation')
    for wsa in WsAnnotation.objects.exclude(replaced_by=None):
        wsa.replacements.add(wsa.replaced_by)
        wsa.save()

class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0153_wsannotation_replacements'),
    ]

    operations = [
            migrations.RunPython(copy_replacements)
    ]
