# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0154_auto_20200130_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wsannotation',
            name='replaced_by',
        ),
    ]
