# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0155_remove_wsannotation_replaced_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsannotation',
            name='replacements',
            field=models.ManyToManyField(related_name='replacement_for', to='browse.WsAnnotation'),
        ),
    ]
