# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0153_auto_20200130_1020'),
        ('browse', '0153_auto_20200130_1106'),
        ('browse', '0156_auto_20200130_1257'),
    ]

    operations = [
    ]
