# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-07 19:19
from __future__ import unicode_literals

from django.db import migrations

def copy_defaults(apps, schema_editor):
    Workspace = apps.get_model('browse', 'Workspace')
    from browse.models import VersionDefault
    matches = [
            ['DiseaseShortName', 'short_name'],
            ['EvalDrugset', 'eval_drugset'],
            ['DpiDataset', 'dpi_default'],
            ['PpiDataset', 'ppi_default'],
            ['DpiThreshold', 'dpi_thresh_default'],
            ['PpiThreshold', 'ppi_thresh_default'],
            ['IntolerableUniprotsSet', 'unwanted_ps_default'],
            ['DiseaseNonNovelUniprotsSet', 'nonnovel_ps_default'],
            ]
    for ws in Workspace.objects.all():
        change_list = []
        for def_name, ws_name in matches:
            value = getattr(ws, ws_name, None)
            if value:
                change_list.append([def_name, value])

        VersionDefault.set_defaults(ws.id, change_list, 'legacy_migrate')

class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0157_merge_20200205_1046'),
    ]

    operations = [
            migrations.RunPython(copy_defaults)
    ]
