# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-07 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0158_auto_20200207_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='dpi_default',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='dpi_thresh_default',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='eval_drugset',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='nonnovel_ps_default',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='ppi_default',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='ppi_thresh_default',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='unwanted_ps_default',
        ),
    ]
