# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-12 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0159_auto_20200207_1204'),
        ('browse', '0158_wsannotation_txr_id'),
    ]

    operations = [
    ]
