# Generated by Django 2.2.10 on 2020-03-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0160_merge_20200211_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeaccession',
            name='alt_ids',
            field=models.TextField(blank=True, default=''),
        ),
    ]
