# Generated by Django 2.2.10 on 2020-03-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0161_aeaccession_alt_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinUploadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=256)),
                ('ok', models.BooleanField(default=False)),
            ],
        ),
    ]
