# Generated by Django 2.2.10 on 2020-03-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0162_auto_20200318_1346'),
        ('browse', '0162_proteinuploadstatus'),
    ]

    operations = [
    ]
