# Generated by Django 2.2.10 on 2020-04-24 18:02

from django.db import migrations

def upgrade_tissue_sets(apps,schema_editor):
    # make sure each workspace has a miRNA tissue set,
    # with the flag set properly
    Workspace = apps.get_model('browse','Workspace')
    TissueSet = apps.get_model('browse','TissueSet')
    for ws in Workspace.objects.all():
        try:
            ts = ws.tissueset_set.get(name='miRNA')
            if not ts.miRNA: 
                ts.miRNA = True
                ts.save()
        except TissueSet.DoesNotExist:
            TissueSet.objects.create(ws=ws,name='miRNA',miRNA=True)

class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0163_merge_20200325_0938'),
    ]

    operations = [
        migrations.RunPython(upgrade_tissue_sets),
    ]
