# Generated by Django 2.2.10 on 2020-07-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0164_auto_20200424_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugSetChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('user', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('added', models.ManyToManyField(related_name='wsa_added', to='browse.WsAnnotation')),
                ('drugset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.DrugSet')),
                ('removed', models.ManyToManyField(related_name='wsa_removed', to='browse.WsAnnotation')),
            ],
        ),
    ]
