# Generated by Django 2.2.10 on 2020-07-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_auto_20200531_1413'),
        ('browse', '0165_drugsetchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='WsaAgentAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=1024)),
                ('former_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.Drug')),
                ('wsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.WsAnnotation')),
            ],
        ),
    ]
