# Generated by Django 2.2.10 on 2020-07-28 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0166_wsaagentaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescreenFilterAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_filters', models.TextField(blank=True, default='')),
                ('user', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('prescreen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Prescreen')),
            ],
        ),
    ]
