# Generated by Django 2.2.16 on 2020-09-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0167_prescreenfilteraudit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drugsplit',
            unique_together={('ws', 'name')},
        ),
    ]
