# Generated by Django 2.2.16 on 2020-10-20 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200625_1100'),
        ('browse', '0169_auto_20201006_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='hitsel_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ws_hitsel_note', to='notes.Note'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='disease_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='notes.Note'),
        ),
    ]
