# Generated by Django 2.2.17 on 2020-11-30 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200625_1100'),
        ('browse', '0170_auto_20201020_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTargetAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='browse.Protein')),
            ],
        ),
    ]
