# Generated by Django 2.2.17 on 2021-01-20 19:08

from django.db import migrations, models
import django.db.models.deletion

def func(apps, schema_editor):
    # Copy status and update times for this.
    StageStatus = apps.get_model('browse', 'StageStatus')
    ge_statuses = StageStatus.objects.filter(stage_name='GeneExpressionData')

    for stat in ge_statuses:
        obj, is_new = StageStatus.objects.get_or_create(
                ws=stat.ws,
                stage_name='AbundanceValidated'
                )
        obj.status = stat.status
        obj.save()
        # Separately update the timestamp to work around the auto_now logic on save.
        StageStatus.objects.filter(pk=obj.id).update(changed_on=stat.changed_on)

class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0172_workspace_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=50)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.StageStatus')),
            ],
        ),
        migrations.RunPython(func, lambda *args, **kwargs: None),
    ]
