# Generated by Django 2.2.17 on 2021-01-15 00:31

from django.db import migrations, models


def set_created_dates(apps, schema_editor):
    Workspace = apps.get_model('browse', 'Workspace')
    all_ws = {ws.id: ws for ws in Workspace.objects.all()}

    # This works because we always created workspace via the admin portal
    from django.contrib.admin.models import LogEntry
    logs = LogEntry.objects.filter(content_type_id=11)
    earliest = {}
    for log in logs:
        ws_id = int(log.object_id)
        if ws_id not in all_ws:
            continue
        created = log.action_time
        if ws_id not in earliest:
            earliest[ws_id] = created
        else:
            earliest[ws_id] = min(earliest[ws_id], created)
    
    from tqdm import tqdm
    for ws in tqdm(all_ws.values()):
        if ws.id in earliest:
            ws.created = earliest[ws.id]
            ws.save()
        else:
            print("Missing creation date for ", ws, ws.id)

class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0171_globaltargetannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunPython(
            set_created_dates,
            reverse_code=lambda *args, **kwargs: None)
    ]
