# Generated by Django 2.2.19 on 2021-03-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0172_stagestatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeaccession',
            name='experiment_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aesearch',
            name='version',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
