# Generated by Django 2.2.19 on 2021-03-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0173_auto_20210318_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeaccession',
            name='num_samples',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
