# Generated by Django 2.2.20 on 2021-05-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0175_auto_20210331_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissueset',
            name='species',
            field=models.IntegerField(choices=[(0, 'Human'), (1, 'Mouse'), (2, 'Rat'), (3, 'Dog'), (4, 'Zebrafish')], default=0),
        ),
    ]
