# Generated by Django 2.2.24 on 2021-08-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0176_tissueset_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='gwasdataset',
            name='v2d_threshold',
            field=models.FloatField(default=1.0),
        ),
    ]
