# Generated by Django 2.2.24 on 2021-08-27 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0003_processwait'),
        ('browse', '0177_gwasdataset_v2d_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_job', to='runner.Process')),
                ('wf_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wf_job', to='runner.Process')),
            ],
        ),
    ]
