# Generated by Django 2.2.24 on 2022-03-15 21:04

from django.db import migrations

def port_species_data(apps, schema_editor):
    # Populate the new 'species' column for legacy data, based on the
    # deprecated nonhumans column. Nonhumans will be removed in a later
    # migration.
    #
    # The django documentation recommends using get_model, but the enum
    # doesn't seem to be available via that route, so we import the model
    # 2 ways.
    AeSearch = apps.get_model('browse','AeSearch')
    from browse.models import AeSearch as NewModel
    for aes in AeSearch.objects.all():
        if aes.nonhumans:
            aes.species = NewModel.species_vals.any
        else:
            aes.species = NewModel.species_vals.human
        aes.save()

class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0179_auto_20220315_1341'),
    ]

    operations = [
        migrations.RunPython(port_species_data),
    ]
