# Generated by Django 2.2.24 on 2022-05-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0181_remove_aesearch_nonhumans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagestatus',
            name='status',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Active'), (2, 'Complete'), (3, 'Verified')], default=0),
        ),
    ]
