# Generated by Django 3.2.15 on 2022-08-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0182_auto_20220502_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='recommended',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='cross_compare',
            field=models.BooleanField(null=True),
        ),
    ]
