# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-10 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('runner', '0001_initial'), ('runner', '0002_auto_20141206_1314'), ('runner', '0003_auto_20150115_1055'), ('runner', '0004_process_created'), ('runner', '0005_auto_20150303_1103'), ('runner', '0006_process_user'), ('runner', '0007_auto_20151202_1534'), ('runner', '0008_auto_20151202_1536'), ('runner', '0009_load'), ('runner', '0010_auto_20160108_1724'), ('runner', '0011_remove_process_status_file'), ('runner', '0012_process_invalidated'), ('runner', '0013_reservedjobname'), ('runner', '0014_load_slow'), ('runner', '0015_process_role'), ('runner', '0016_auto_20171114_1306'), ('runner', '0017_auto_20190923_1714'), ('runner', '0018_auto_20191011_1433'), ('runner', '0018_auto_20191011_1354'), ('runner', '0019_merge_20191016_1531')]

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('rundir', models.CharField(max_length=1024)),
                ('cmd', models.CharField(max_length=1024)),
                ('status', models.IntegerField(choices=[(0, b'Queued'), (1, b'Running'), (2, b'Succeeded'), (3, b'Failed'), (4, b'Failed Prereq')])),
                ('wait_for', models.ManyToManyField(to='runner.Process')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
                ('settings_json', models.TextField(blank=True, default=b'')),
                ('sw_version', models.CharField(blank=True, default=b'', max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.CharField(blank=True, default=b'', max_length=70)),
                ('completed', models.DateTimeField(null=True)),
                ('exit_code', models.IntegerField(null=True)),
                ('started', models.DateTimeField(null=True)),
                ('invalidated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.IntegerField()),
                ('want', models.CharField(blank=True, default='', max_length=250)),
                ('got', models.CharField(blank=True, default='', max_length=250)),
                ('slow', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReservedJobname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.Process')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='role',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='process',
            name='settings_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterIndexTogether(
            name='process',
            index_together=set([('status',), ('name',)]),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.IntegerField(choices=[(0, 'Queued'), (1, 'Running'), (2, 'Succeeded'), (3, 'Failed'), (4, 'Failed Prereq')]),
        ),
        migrations.AlterField(
            model_name='process',
            name='sw_version',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='process',
            name='user',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='process',
            name='settings_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.IntegerField(choices=[(0, 'Queued'), (1, 'Running'), (2, 'Succeeded'), (3, 'Failed'), (4, 'Failed Prereq')]),
        ),
        migrations.AlterField(
            model_name='process',
            name='sw_version',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='process',
            name='user',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
