# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_squashed_0019_merge_20191016_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='job',
            field=models.IntegerField(unique=True),
        ),
    ]
