# Generated by Django 2.2.15 on 2020-09-01 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_auto_20200130_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessWait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('waited_for', models.TextField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.Process')),
            ],
        ),
    ]
