# Generated by Django 3.2.15 on 2022-11-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0004_auto_20220518_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=70)),
                ('status', models.IntegerField(choices=[(0, 'Idle'), (1, 'Pending'), (2, 'Active')])),
                ('detail', models.TextField()),
            ],
        ),
    ]
