# Generated by Django 3.2.15 on 2022-11-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0005_maintenancelock'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelock',
            name='pid',
            field=models.IntegerField(null=True),
        ),
    ]
