
versions = {
        8:dict(
                description='Dec2022 ETL update',
                VCF_VERSION='GCF_000001405.39',
                GRASP_VER='v1',
                GWASCAT_VER='v13',
                PHEWAS_VER='v2',
                UKBB_VER='v3',
                FINNGEN_VER='v1',
                ),
        7:dict(
                description='Sep2022 ETL update',
                VCF_VERSION='GCF_000001405.39',
                GRASP_VER='v1',
                GWASCAT_VER='v12',
                PHEWAS_VER='v2',
                UKBB_VER='v3',
                FINNGEN_VER='v1',
                ),
        6:dict(
                description='Jun2022 ETL update',
                VCF_VERSION='GCF_000001405.39',
                GRASP_VER='v1',
                GWASCAT_VER='v11',
                PHEWAS_VER='v2',
                UKBB_VER='v3',
                FINNGEN_VER='v1',
                ),
        5:dict(
                description='1Mar2022 ETL update',
                VCF_VERSION='GCF_000001405.39',
                GRASP_VER='v1',
                GWASCAT_VER='v10',
                PHEWAS_VER='v2',
                UKBB_VER='v3',
                FINNGEN_VER='v1',
                ),
        4:dict(
                description='1Dec2021 ETL update',
                VCF_VERSION='GCF_000001405.39',
                GRASP_VER='v1',
                GWASCAT_VER='v9',
                PHEWAS_VER='v2',
                UKBB_VER='v3',
                FINNGEN_VER='v1',
                ),
        3:dict(
                description='16Aug2021 ETL update',
                VCF_VERSION='GCF_000001405.39',
                GRASP_VER='v1',
                GWASCAT_VER='v8',
                PHEWAS_VER='v2',
                UKBB_VER='v3',
                FINNGEN_VER='v1',
                ),
        2:dict(
                description='Adding finngen',
                VCF_VERSION='GCF_000001405.39',
                GRASP_VER='v1',
                GWASCAT_VER='v7',
                PHEWAS_VER='v2',
                UKBB_VER='v3',
                FINNGEN_VER='v1',
                ),
        1:dict(
                description='First version with split gwas',
                VCF_VERSION='GCF_000001405.39',
                GRASP_VER='v1',
                GWASCAT_VER='v7',
                PHEWAS_VER='v2',
                UKBB_VER='v3',
                ),
}
