# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-17 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_squashed_0023_merge_20191016_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpiMergeKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('dpimerge_key', models.CharField(max_length=256)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.Drug')),
            ],
        ),
    ]
