# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_dpimergekey'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together=set([('name', 'key_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='prop',
            unique_together=set([('name',)]),
        ),
    ]
