# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-14 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_auto_20200130_1106'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='dpimergekey',
            index_together=set([('version', 'dpimerge_key')]),
        ),
    ]
