# Generated by Django 2.2.10 on 2020-03-23 20:16

from django.db import migrations


forward_sql = """CREATE INDEX custom_drugs_blob_index
    ON drugs_blob(value(32))
    """
reverse_sql = """DROP INDEX custom_drugs_blob_index ON drugs_blob"""


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_auto_20200214_1107'),
    ]

    operations = [
        migrations.RunSQL(
         sql=forward_sql,
         reverse_sql=reverse_sql
         ),
    ]
