# Generated by Django 2.2.15 on 2020-09-01 15:58

from django.db import migrations


def add_native_id(apps, schema_editor):
    Prop = apps.get_model('drugs', 'Prop')
    Tag = apps.get_model('drugs', 'Tag')
    Drug = apps.get_model('drugs', 'Drug')
    Collection = apps.get_model('drugs', 'Collection')

    # When this runs as part of install.sh, you won't have imported this yet, so
    # do it automatically.
    Prop.objects.get_or_create(name='native_id', prop_type=0, multival=False)

    all_key_names = list(Collection.objects.all().values_list('key_name', flat=True))

    native_prop = Prop.objects.get(name='native_id')
    from tqdm import tqdm
    qs = Drug.objects.all().values('collection__key_name', 'id')

    print("Bulk lookup of all existing native ids")
    drug2native = dict(Tag.objects.filter(prop__name__in=all_key_names).values_list('drug__id', 'value'))
    print("Listing out all native keys to create")
    to_create = []
    for data in tqdm(list(qs)):
        collection_prop_id = data['collection__key_name']
        drug_id = data['id']
        native_id_val = drug2native[drug_id]
        to_create.append(Tag(
            drug_id=drug_id,
            prop=native_prop,
            value=native_id_val,
        ))
    print(f"Creating {len(to_create)} tags")
    from dtk.parallel import chunker
    for chunk in chunker(to_create, chunk_size=2000, progress=True):
        Tag.objects.bulk_create(chunk)

class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_auto_20200531_1413'),
    ]

    operations = [
        migrations.RunPython(add_native_id)
    ]
