# Generated by Django 2.2.17 on 2020-11-20 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0008_auto_20200901_0858'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='tag',
            index_together={('prop', 'value'), ('prop', 'drug'), ('value',)},
        ),
    ]
